# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-04 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plays',
            name='position',
        ),
        migrations.AddField(
            model_name='plays',
            name='points',
            field=models.IntegerField(default=999999),
        ),
        migrations.AlterField(
            model_name='boardgames',
            name='maxplayers',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='boardgames',
            name='minage',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='boardgames',
            name='minplayers',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='boardgames',
            name='usersrated',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='boardgames',
            name='yearpublished',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
