# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_templates_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
