# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20170203_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedpoints',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
